name: Update SonyLIV Channels

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch with Proxy
        run: |
          # SOCKS5 Amazon Proxy
          RESPONSE=$(curl -x "socks5://40.192.18.48:12874" -L --compressed \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            -H "Accept: */*" \
            -H "Accept-Encoding: gzip" \
            -H "Cache-Control: no-cache, no-store" \
            --connect-timeout 20 \
            --max-time 40 \
            "https://apiv4.sonyliv.com/AGL/4.7/A/ENG/MWEB/IN/BR/CONTENT/VIDEOURL/VOD/1000051729")

          VIDEO_URL=$(echo "$RESPONSE" | grep -o '"videoURL":"[^"]*' | cut -d'"' -f4 | head -1)
          
          if [ -n "$VIDEO_URL" ]; then
            HDNEA=$(echo "$VIDEO_URL" | grep -o 'hdnea=[^&" ]*')
            if [ -f "Slivtv.json" ]; then
              sed -i "s|hdnea=[^&\"' ]*|${HDNEA}|g" "Slivtv.json"
              echo "SUCCESS: Token updated in Slivtv.json"
            else
              echo "FAILURE: Slivtv.json not found."
              exit 1
            fi
          else
            echo "FAILURE: Proxy blocked or no data."
            exit 1
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GithubBot"
          git config --global user.email "bot@github.com"
          git add Slivtv.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Sony Token: $(date)" && git push)
